
/**
 * Generated by http://www.json-generator.com/
 */
var SALES_DATA = [
  {
    "_id": "58094031b0fd527516ae985e",
    "product": "Snow",
    "to": "Mcguire Michael",
    "dealer": "Tomy DeVito",
    "ammount": "$1,034.27",
    "date": "2015-03-25"
  },
  {
    "_id": "58094031264903335cc65399",
    "product": "White",
    "to": "Julianne Roman",
    "dealer": "Henry Hill",
    "ammount": "$1,284.95",
    "date": "2015-07-21"
  },
  {
    "_id": "580940318ec056932e6214f6",
    "product": "Sugar",
    "to": "Allison Kelley",
    "dealer": "Tony Montana",
    "ammount": "$503.82",
    "date": "2015-01-04"
  },
  {
    "_id": "58094031d6a405f3683dea31",
    "product": "Sugar",
    "to": "Gilmore Garcia",
    "dealer": "Tony Montana",
    "ammount": "$353.32",
    "date": "2015-03-30"
  },
  {
    "_id": "5809403123ab2c0cdf2e251c",
    "product": "Snow",
    "to": "Payne Bailey",
    "dealer": "Henry Hill",
    "ammount": "$420.90",
    "date": "2015-12-05"
  },
  {
    "_id": "58094031e5cdd768a7ddb917",
    "product": "White",
    "to": "Janice Cash",
    "dealer": "Tomy DeVito",
    "ammount": "$696.81",
    "date": "2014-08-13"
  },
  {
    "_id": "580940312de14069910b33bc",
    "product": "White",
    "to": "Mayo Lowe",
    "dealer": "Tony Montana",
    "ammount": "$1,469.85",
    "date": "2016-02-24"
  },
  {
    "_id": "580940319c497cf314d2fabc",
    "product": "Pearl",
    "to": "Dennis Mcconnell",
    "dealer": "Vinny",
    "ammount": "$449.35",
    "date": "2016-03-01"
  },
  {
    "_id": "58094031e29df81c8d214cba",
    "product": "Snow",
    "to": "Nichole Golden",
    "dealer": "Tony Montana",
    "ammount": "$214.36",
    "date": "2016-03-28"
  },
  {
    "_id": "58094031474e4b6052a96835",
    "product": "Clouds",
    "to": "Bolton Pearson",
    "dealer": "Tomy DeVito",
    "ammount": "$751.38",
    "date": "2014-09-05"
  },
  {
    "_id": "58094031437513832725af11",
    "product": "White",
    "to": "Georgette House",
    "dealer": "Tony Montana",
    "ammount": "$220.61",
    "date": "2014-06-16"
  },
  {
    "_id": "58094031a77599fa1b08ceee",
    "product": "White",
    "to": "Pena Mcclain",
    "dealer": "Tomy DeVito",
    "ammount": "$740.39",
    "date": "2014-07-25"
  },
  {
    "_id": "5809403192fe8c71af36e46d",
    "product": "Pearl",
    "to": "Bush Farley",
    "dealer": "Manny Ribera",
    "ammount": "$1,095.46",
    "date": "2015-12-09"
  },
  {
    "_id": "580940316d3c1dbdd4df1f6f",
    "product": "Snow",
    "to": "Lloyd Klein",
    "dealer": "Manny Ribera",
    "ammount": "$1,100.71",
    "date": "2015-06-03"
  },
  {
    "_id": "58094031bf0a7a202be550eb",
    "product": "White",
    "to": "Dollie Wagner",
    "dealer": "Manny Ribera",
    "ammount": "$727.49",
    "date": "2015-08-22"
  },
  {
    "_id": "58094031f8b9e1f48cd56972",
    "product": "White",
    "to": "Elizabeth Kerr",
    "dealer": "Vinny",
    "ammount": "$1,187.35",
    "date": "2016-07-06"
  },
  {
    "_id": "58094031e08faef53de0f0ca",
    "product": "Pearl",
    "to": "Guerrero Snider",
    "dealer": "Manny Ribera",
    "ammount": "$303.12",
    "date": "2015-11-06"
  },
  {
    "_id": "5809403123ebeb4a575a00a5",
    "product": "Clouds",
    "to": "Elnora Davidson",
    "dealer": "Tony Montana",
    "ammount": "$679.83",
    "date": "2014-10-27"
  },
  {
    "_id": "58094031274db4d076ed1477",
    "product": "White",
    "to": "Roman Long",
    "dealer": "Tony Montana",
    "ammount": "$1,081.55",
    "date": "2016-10-05"
  },
  {
    "_id": "580940311b2851706be25118",
    "product": "Snow",
    "to": "Heidi Carver",
    "dealer": "Henry Hill",
    "ammount": "$602.84",
    "date": "2015-04-20"
  },
  {
    "_id": "58094031d366cc12b191c864",
    "product": "White",
    "to": "Amparo Mercer",
    "dealer": "Tony Montana",
    "ammount": "$166.34",
    "date": "2014-03-07"
  },
  {
    "_id": "580940319e881f8646e49c96",
    "product": "Pearl",
    "to": "Imelda Townsend",
    "dealer": "Tony Montana",
    "ammount": "$708.54",
    "date": "2014-01-19"
  },
  {
    "_id": "58094031b4aa1498f1f327c1",
    "product": "White",
    "to": "Stevenson Ray",
    "dealer": "Henry Hill",
    "ammount": "$1,247.75",
    "date": "2015-10-05"
  },
  {
    "_id": "58094031ed9cc256fcb48ddd",
    "product": "White",
    "to": "Calderon Kim",
    "dealer": "Henry Hill",
    "ammount": "$1,354.69",
    "date": "2015-01-18"
  },
  {
    "_id": "5809403127c203b385961391",
    "product": "Snow",
    "to": "Mathews Silva",
    "dealer": "Tomy DeVito",
    "ammount": "$118.19",
    "date": "2016-06-06"
  },
  {
    "_id": "58094031cbca9609fbe0081b",
    "product": "Snow",
    "to": "Mooney Fry",
    "dealer": "Henry Hill",
    "ammount": "$264.02",
    "date": "2014-11-11"
  },
  {
    "_id": "5809403123f7b0ff26cb2268",
    "product": "Snow",
    "to": "Stewart Arnold",
    "dealer": "Vinny",
    "ammount": "$274.71",
    "date": "2016-07-09"
  },
  {
    "_id": "580940312c82a78180f26ec7",
    "product": "Snow",
    "to": "Margret Benson",
    "dealer": "Vinny",
    "ammount": "$676.68",
    "date": "2016-02-09"
  },
  {
    "_id": "58094031b691d1cf59b01ecf",
    "product": "Sugar",
    "to": "Ramos Watkins",
    "dealer": "Tomy DeVito",
    "ammount": "$1,072.65",
    "date": "2014-08-22"
  },
  {
    "_id": "580940315babdf9c26426e72",
    "product": "White",
    "to": "Sanders Hansen",
    "dealer": "Vinny",
    "ammount": "$359.09",
    "date": "2016-02-21"
  }
];